server:
  port: 8081

xxl:
  job:
    # 调度中心部署根地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔
    admin-addresses: http://127.0.0.1:9080/xxl-job-admin
    # 执行器通讯TOKEN [选填]：非空时启用
    access-token: default_token
    executor:
      # 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname: spring-default-executor
      # 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址
      address:
      # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用
      ip:
      # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口
      port: 9999
      logpath: ./xxl-job/jobhandler
      logretentiondays: 30
